title: 'Event Programme'
image: galleries/2024_gallery/2024_gallery_10.jpg
updated_by: 4d25b1f6-2153-41a7-9460-d89cdfaa8fa1
updated_at: 1754552410
blueprint: agenda
order: 30
localizations:
  ar:
    title: 'جدول الفعاليات'
    slug: event-programme
    updated_by: c970e8d9-e297-424a-bad0-93b7dab4d61d
    updated_at: 1756467102
